### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by stefanon** [gnu-octave/octave-mqtt#1]
I have this error trying the install in Octave: 
>> pkg install -forge mqtt
configure: error: paho-mqtt is required to install Octave mqtt
and I've already installed the paho-mqtt C client library on my system (linux), any suggestion? 
thank you

**Comment by lostbard** [comment]
Have you also installed the paho-dev  package as well ?

In ubuntu I believe its libpaho-mqtt-dev 
fedora: paho-c-devel

**Comment by lostbard** [comment]
Assuming since no additional follow up that the dev package was missing
